# Generated by Django 3.0.8 on 2020-07-23 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('cryptid_other_name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('first_mentioned', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cryptid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Cryptid')),
            ],
        ),
    ]
