# Generated by Django 3.0.8 on 2020-07-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptid',
            name='img',
            field=models.URLField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
