# Generated by Django 3.0.8 on 2020-07-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200722_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptid',
            name='cryptid_name',
            field=models.TextField(default='unknown'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cryptid',
            name='cryptid_other_name',
            field=models.TextField(default='unknown'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cryptid',
            name='cryptit_location',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cryptid',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cryptid',
            name='cryptid_text',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
