# Generated by Django 3.0.8 on 2020-07-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20200723_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryptid',
            old_name='cryptid_text',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='cryptid',
            name='cryptid_name',
        ),
        migrations.AlterField(
            model_name='cryptid',
            name='cryptid_other_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
