# Generated by Django 3.0.8 on 2020-07-23 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20200723_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryptid',
            old_name='cryptid_name',
            new_name='name',
        ),
    ]
